name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    uses: Start9Labs/shared-workflows/.github/workflows/release.yml@6f3216afb2818e350e7ce21d27101427cbbf34db
    with:
      # FREE_DISK_SPACE: true
      RELEASE_REGISTRY: ${{ vars.REGISTRY }} # Optional registry publishing target
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY }} # Required
    permissions:
      contents: write
